### PR TITLE
Install chef-client for specs

### PR DESCRIPTION
**Pull request by danielsdeleo**
I just installed a new Ruby, which didn't have a chef gem. In this state, the specs did not pass.

### CODE REVIEW

**Comment by danielsdeleo** [comment]
Without this, if you don't happen to have chef installed, you'll get:

```
Finished in 1.49 seconds (files took 0.22512 seconds to load)
42 examples, 12 failures

Failed examples:

rspec ./spec/integration/chef_runner_spec.rb:6 # ChefAcceptance::ChefRunner calls run
rspec ./spec/integration/chef_runner_spec.rb:17 # ChefAcceptance::ChefRunner calls run and picks up shared cookbooks
rspec './spec/integration/cli_spec.rb[1:2:1:1]' # ChefAcceptance::Cli for a valid test suite with provision command runs successfully
rspec './spec/integration/cli_spec.rb[1:2:2:1]' # ChefAcceptance::Cli for a valid test suite with verify command runs successfully
rspec './spec/integration/cli_spec.rb[1:2:3:1]' # ChefAcceptance::Cli for a valid test suite with destroy command runs successfully
rspec ./spec/integration/cli_spec.rb:60 # ChefAcceptance::Cli for a valid test suite with test command runs successfully
rspec ./spec/integration/cli_spec.rb:75 # ChefAcceptance::Cli for a valid test suite with test --force-destroy runs successfully
rspec ./spec/integration/cli_spec.rb:93 # ChefAcceptance::Cli for a failing verify phase in the suite with verify command fails
rspec ./spec/integration/cli_spec.rb:110 # ChefAcceptance::Cli for a failing verify phase in the suite with test command fails
rspec ./spec/integration/cli_spec.rb:127 # ChefAcceptance::Cli for a failing verify phase in the suite with test --force-destroy fails
rspec ./spec/integration/cli_spec.rb:144 # ChefAcceptance::Cli with a regex fails running both of the suites
rspec ./spec/integration/cli_spec.rb:165 # ChefAcceptance::Cli by default fails running both of the suites
```

All caused by not having chef-client

**Comment by sersut** [comment]
:+1: 

We had https://github.com/chef/chef-acceptance/pull/30 but we don't remember what the exact issue was. Let's ship this and see what it was :smile:

**Comment by danielsdeleo** [comment]
doing an ad-hoc build to see what's up: http://manhattan.ci.chef.co/job/chef-trigger-ad_hoc/137/downstreambuildview/

**Comment by danielsdeleo** [comment]
In the ad-hoc build, acceptance has not yet succeeded, but it has run several of the suites with no issues. Gonna merge this and we can revisit if the problem recurs.

**Pull request merged**
