### PR TITLE
Run each suite in a thread

### PR DESCRIPTION
**Pull request by danielsdeleo**
Seems like it can't possibly be this easy?

Running a test build: http://manhattan.ci.chef.co/job/chef-trigger-ad_hoc/139/downstreambuildview/

### CODE REVIEW

**Comment by danielsdeleo** [comment]
Test build with a worker pool and concurrency limited to 3: http://manhattan.ci.chef.co/job/chef-trigger-ad_hoc/142/downstreambuildview/

**Comment by patrick-wright** [comment]
Totally that easy!

**Comment by danielsdeleo** [comment]
With the workers set to 3, this works in Ci: http://manhattan.ci.chef.co/job/chef-test/187/architecture=x86_64,platform=acceptance,project=chef,role=tester/consoleFull

**Comment by mwrock** [comment]
:+1:

**Comment by sersut** [comment]
This is sweet! :+1: 

I think we have some integration spec coverage in `cli_spec.rb` since it's enabled by default. 

I think we can :shipit:

**Pull request merged**
