### PR TITLE
Create temporary files required for chef run under platform tmpdir.

### PR DESCRIPTION
**Pull request by sersut**
Fixes https://github.com/chef/chef-acceptance/issues/36.

/cc: @chef/engineering-services

### CODE REVIEW

**Comment by schisamo** [comment]
@sersut Any chance this could be configurable with a default of `Dir.tmpdir`?

**Comment by sersut** [comment]
For sure we can make it configurable. Do we have any reason to?

**Comment by schisamo** [comment]
@sersut Yes. When we are executing Chef Acceptance in Jenkins or Delivery we'll want these files to land in the job workspace.

**Comment by sersut** [comment]
Hrmmm. Can I ask why? 

Also cc @patrick-wright. We do not have any configuration file for chef-acceptance yet. We can:

1. Introduce a new CLI option.
2. Add a custom hidden ENV variable. 

I would prefer 1 for sure.

**Comment by schisamo** [comment]
@sersut Yes because that is where jobs are supposed to write their temporary and generated data to for archiving, which provides persistence between job runs. Any other location cannot be guaranteed to be 'safe'. For example, this is the spot we dump out the Rspec-generated JUnit XML file (note the `$WORKSPACE/test.xml`):
https://github.com/chef/chef/blob/master/ci/verify-chef.sh#L120

Ditto on Server pipeline's Pedant output (note the `$WORKSPACE/pedant.xml`):
https://github.com/chef-cookbooks/opscode-ci/blob/master/libraries/server_build_pipeline.rb#L110

These locations are also cleaned up between job runs (we completely wipe the workspace) so we don't have to worry about previous job runs data creeping in either.

**Comment by sersut** [comment]
Will have a new PR.

**Pull request closed without merging**
